import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { prepareData, recordCardPayment, assignCardPayments, statementTotals } from '../src/lib/finance.js'
import { monthlyCategoryTrend } from '../src/lib/reporting.js'
import { upcomingSummary } from '../src/lib/upcomingSummary.js'
import { createRepository } from '../src/lib/storage.js'
import config from '../vite.config.js'
import { createServer } from 'vite'
import React from 'react'
import { renderToStaticMarkup } from 'react-dom/server'

const now=new Date(2026,7,29,12),base=()=>prepareData({financeVersion:1,accounts:[{id:'bank',name:'Fictional Bank',type:'checking',balance:2000},{id:'card',name:'Fictional Card',type:'credit',balance:900,limit:2000,apr:20,minimum:40}],cardStatements:[{id:'sep',cardId:'card',dueDate:'2026-09-15',minimum:40}],payments:[],transactions:[],bills:[],billPayments:[],adjustments:[],creditScores:[],extra:0},now)
test('Already included payment is general by default and never changes current balances',()=>{const before=base(),next=recordCardPayment(before,{cardId:'card',bankId:'bank',amount:125,date:'2026-08-01',historical:true,statementId:''},now);assert.deepEqual(next.accounts,before.accounts);assert.equal(next.payments[0].assignmentStatus,'general');assert.equal(statementTotals(next.cardStatements[0],next.payments,now).actualPaid,0);assert.equal(upcomingSummary(next,now)[0].reviewPaymentCount,0)})
test('v0.9.2 historical unassigned records upgrade to general without changing balances',()=>{const raw=base();raw.payments=[{id:'old',cardId:'card',bankId:'bank',amount:50,date:'2026-07-01T12:00:00Z',localDate:'2026-07-01',historical:true,statementId:'',assignmentStatus:'unassigned'}];const before=structuredClone(raw.accounts),next=prepareData(raw,now);assert.deepEqual(next.accounts,before);assert.equal(next.payments[0].assignmentStatus,'general');assert.deepEqual(prepareData(next,now),next)})
test('first v0.9.4 save preserves the exact pre-upgrade browser records',()=>{const raw=base();raw.payments=[{id:'old',cardId:'card',bankId:'bank',amount:50,date:'2026-07-01T12:00:00Z',historical:true,statementId:'',assignmentStatus:'unassigned'}];const original=JSON.stringify(raw),items=new Map([['test',original]]),storage={getItem:key=>items.get(key)||null,setItem:(key,value)=>items.set(key,value)},repo=createRepository(storage,'test'),data=repo.load({});repo.save(data);assert.equal(items.get('test-before-v094'),original);repo.save(data);assert.equal(items.get('test-before-v094'),original)})
test('explicitly assigning historical payment changes only metadata and can satisfy old minimum',()=>{let data=recordCardPayment(base(),{cardId:'card',bankId:'bank',amount:40,date:'2026-08-01',historical:true,statementId:''},now),before=structuredClone(data.accounts);data=assignCardPayments(data,[data.payments[0].id],'sep',now);assert.deepEqual(data.accounts,before);assert.equal(data.payments[0].assignmentStatus,'confirmed');assert.equal(statementTotals(data.cardStatements[0],data.payments,now).remaining,0)})
test('current unassigned payment changes balances once and remains an actionable review',()=>{const before=base(),data=recordCardPayment(before,{cardId:'card',bankId:'bank',amount:25,date:'2026-08-28',historical:false,statementId:''},now);assert.deepEqual(data.accounts.map(a=>a.balance),[1975,875]);assert.equal(data.payments[0].assignmentStatus,'unassigned');assert.equal(upcomingSummary(data,now)[0].reviewPaymentCount,1);const general=assignCardPayments(data,[data.payments[0].id],'__general__',now);assert.deepEqual(general.accounts,data.accounts);assert.equal(upcomingSummary(general,now)[0].reviewPaymentCount,0)})
test('category stacks use cents, six-month leaders plus Other, and preserve monthly net totals',()=>{const entries=[{date:'2026-08-01T12:00:00Z',localDate:'2026-08-01',category:'Dining',amount:100},{date:'2026-08-02T12:00:00Z',localDate:'2026-08-02',category:'Fuel',amount:50},{date:'2026-08-03T12:00:00Z',localDate:'2026-08-03',category:'Dining',amount:-20},{date:'2026-08-04T12:00:00Z',localDate:'2026-08-04',category:'Tiny',amount:.1},{date:'2025-01-01T12:00:00Z',localDate:'2025-01-01',category:'Old noise',amount:9999}];const result=monthlyCategoryTrend(entries,1,now,2),month=result.months[0];assert.deepEqual(result.categories,['Dining','Fuel','Other']);assert.deepEqual(month.values,{Dining:80,Fuel:50,Other:.1});assert.equal(month.total,130.1)})
test('account tiles and stacked categories render without external images and fit built release',async()=>{const server=await createServer({server:{middlewareMode:true},appType:'custom'});try{const {default:Tiles}=await server.ssrLoadModule('/src/AccountTiles.jsx'),{default:Trends}=await server.ssrLoadModule('/src/SpendingTrends.jsx');const tiles=renderToStaticMarkup(React.createElement(Tiles,{accounts:base().accounts,onEdit(){},onRemove(){}})),trends=renderToStaticMarkup(React.createElement(Trends,{entries:[{date:'2026-08-01T12:00:00Z',localDate:'2026-08-01',category:'Dining',amount:25}]}));for(const text of ['Fictional Card','$900.00','45% utilization','Edit','Remove'])assert.ok(tiles.includes(text));assert.ok(!tiles.includes('<img'));for(const text of ['Net spending by category','Dining','aria-label="Aug Dining: $25"','type="button"'])assert.ok(trends.includes(text))}finally{await server.close()};const output=config.plugins[0].transform(await readFile(new URL('../src/App.jsx',import.meta.url),'utf8'),'/src/App.jsx');assert.match(output,/<AccountTiles accounts=\{data.accounts\}/);assert.match(output,/Tile color/);assert.match(output,/accent:form.accent\|\|old\?\.accent/);assert.match(output,/const VERSION='0\.9\.4'/)})
