import test from 'node:test'
import assert from 'node:assert/strict'
import { anonymizeDiagnosticData, diagnosticPayload } from '../src/lib/diagnosticExport.js'

const source={financeVersion:1,accounts:[{id:'bank',name:'My Real Bank',type:'checking',balance:1200},{id:'card',name:'Real Rewards Card',type:'credit',balance:500}],transactions:[{id:'t1',kind:'purchase',merchant:'Private Shop',accountId:'card',amount:25,date:'2026-08-01T12:00:00Z',category:'Shopping'},{id:'t2',kind:'purchase',merchant:'private shop',accountId:'card',amount:15,date:'2026-08-02T12:00:00Z',category:'Shopping'},{id:'t3',kind:'income',merchant:'Employer Name',accountId:'bank',amount:1000,date:'2026-08-03T12:00:00Z',category:'Income'}],payments:[{id:'p1',cardId:'card',cardName:'Real Rewards Card',bankId:'bank',bankName:'My Real Bank',amount:100,date:'2026-08-04T12:00:00Z'}],bills:[{id:'b1',name:'Specific Streaming Service',amount:20}],billPayments:[{id:'bp1',billId:'b1',billName:'Specific Streaming Service',bankId:'card',bankName:'Real Rewards Card',amount:20,date:'2026-08-05T12:00:00Z'}],adjustments:[{id:'a1',accountId:'bank',before:1,after:2,delta:1,date:'2026-08-06T12:00:00Z',reason:'Personal explanation'}],creditScores:[{id:'s1',score:740,date:'2026-08-07',source:'Aura',bureau:'Equifax',model:'VantageScore 3.0'}]}

test('diagnostic export removes names while preserving audit relationships and values',()=>{const result=anonymizeDiagnosticData(source),text=JSON.stringify(result);for(const secret of ['My Real Bank','Real Rewards Card','Private Shop','private shop','Employer Name','Specific Streaming Service','Personal explanation'])assert.ok(!text.includes(secret));assert.equal(result.accounts[0].name,'Cash Account 1');assert.equal(result.accounts[1].name,'Credit Card 1');assert.equal(result.transactions[0].merchant,result.transactions[1].merchant);assert.equal(result.payments[0].cardName,result.accounts[1].name);assert.equal(result.billPayments[0].billName,result.bills[0].name);assert.equal(result.transactions[0].amount,25);assert.deepEqual(result.creditScores,source.creditScores);assert.equal(source.accounts[0].name,'My Real Bank')})

test('diagnostic payload is visibly non-restorable and carries a privacy warning',()=>{const payload=diagnosticPayload(source,{version:'0.9.5',exportedAt:'2026-09-03T12:00:00.000Z'});assert.equal(payload.schema,'debt-free-anonymized-diagnostic-v1');assert.equal(payload.restoreCompatible,false);assert.match(payload.privacyNotice,/remain sensitive/);assert.equal(payload.version,'0.9.5')})
