import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { prepareData, saveRecurringBill, hasDuplicateLedgerTransaction } from '../src/lib/finance.js'
import { analyzeDataHealth } from '../src/lib/dataHealth.js'
import config from '../vite.config.js'

const now=new Date(2026,8,3,12)
const base=()=>prepareData({financeVersion:1,accounts:[{id:'bank',name:'Bank',type:'checking',balance:1000},{id:'card',name:'Card',type:'credit',balance:500,limit:1000,minimum:25,apr:20,reconciledAt:'2026-09-01T12:00:00Z'}],transactions:[],payments:[],bills:[],billPayments:[],creditScores:[],cardStatements:[{id:'statement',cardId:'card',dueDate:'2026-09-20',minimum:25,needsReview:false}],billCycles:[],adjustments:[],extra:0},now)

test('editing a recurring bill updates only future unconfirmed unpaid occurrences',()=>{const data=base();data.bills=[{id:'music',name:'Music',amount:17.75,dueDay:24,nextDueDate:'2026-08-27',frequency:'monthly',active:true,accountId:'card'}];data.billCycles=[{id:'past',billId:'music',dueDate:'2026-08-24',expectedAmount:17.75,actualAmount:20.89},{id:'future',billId:'music',dueDate:'2026-09-24',expectedAmount:17.75,actualAmount:null}];data.billPayments=[{id:'paid',billId:'music',cycleId:'past',bankId:'card',amount:20.89,date:'2026-08-27T12:00:00Z',localDate:'2026-08-27'}];const next=saveRecurringBill(data,{...data.bills[0],amount:20.89,nextDueDate:'2026-09-27'},now);assert.deepEqual(next.billCycles.find(c=>c.id==='past'),data.billCycles[0]);assert.equal(next.billPayments[0].amount,20.89);assert.equal(next.billCycles.some(c=>c.id==='future'),false);const future=next.billCycles.find(c=>c.dueDate==='2026-09-27');assert.equal(future.expectedAmount,20.89);assert.equal(next.bills[0].dueDay,27)})

test('saving a stale next bill date advances it without creating a phantom overdue occurrence',()=>{const data=base();data.bills=[{id:'music',name:'Music',amount:17.75,dueDay:27,nextDueDate:'2026-08-27',frequency:'monthly',active:true,accountId:'card'}];data.billCycles=[{id:'old',billId:'music',dueDate:'2026-08-24',expectedAmount:17.75,actualAmount:20.89},{id:'wrong-future',billId:'music',dueDate:'2026-09-24',expectedAmount:17.75,actualAmount:null}];const next=saveRecurringBill(data,{...data.bills[0],amount:20.89},now);assert.equal(next.bills[0].nextDueDate,'2026-09-27');assert.ok(next.billCycles.some(c=>c.dueDate==='2026-09-27'&&c.expectedAmount===20.89));assert.equal(next.billCycles.some(c=>c.dueDate==='2026-08-27'),false)})

test('exact activity duplicates are detected while edits ignore their own record',()=>{const data=base(),entry={id:'one',kind:'purchase',accountId:'card',merchant:'Shop',amount:3,date:'2026-05-30T12:00:00Z',localDate:'2026-05-30'};data.transactions=[entry];const form={accountId:'card',merchant:' shop ',amount:'3.00',date:'2026-05-30'};assert.equal(hasDuplicateLedgerTransaction(data,form,'purchase'),true);assert.equal(hasDuplicateLedgerTransaction(data,{...form,id:'one'},'purchase'),false)})

test('data health finds duplicate activity, schedule conflicts, stale checks and score jumps without mutation',()=>{const data=base(),original=structuredClone(data);data.transactions=[{id:'a',kind:'purchase',accountId:'card',merchant:'Shop',amount:3,date:'2026-05-30T12:00:00Z',localDate:'2026-05-30'},{id:'b',kind:'purchase',accountId:'card',merchant:'shop',amount:3,date:'2026-05-30T12:00:00Z',localDate:'2026-05-30'}];data.bills=[{id:'bill',name:'Music',amount:20.89,dueDay:27,nextDueDate:'2026-08-27',frequency:'monthly',active:true}];data.billCycles=[{id:'cycle',billId:'bill',dueDate:'2026-09-24',expectedAmount:17.75,actualAmount:null}];data.creditScores=[{id:'s1',score:675,date:'2026-01-01',source:'Aura',bureau:'Experian',model:'VantageScore 3.0'},{id:'s2',score:742,date:'2026-02-01',source:'Aura',bureau:'Experian',model:'VantageScore 3.0'}];const result=analyzeDataHealth(data,now);for(const kind of ['duplicate','bill','score'])assert.ok(result.issues.some(x=>x.kind===kind));assert.deepEqual(original.accounts,data.accounts)})

test('release uses editable scores, data health, duplicate protection and v0.9.9',async()=>{const source=await readFile(new URL('../src/App.jsx',import.meta.url),'utf8'),output=config.plugins[0].transform(source,'/src/App.jsx');assert.match(output,/CreditScoreTracker entries=\{creditScores\} onSave=\{saveCreditScore\}/);assert.match(output,/<DataHealth data=\{data\} update=\{update\}/);assert.match(output,/hasDuplicateLedgerTransaction/);assert.match(output,/saveRecurringBill/);assert.doesNotMatch(output,/function CreditScoreTracker/);assert.match(output,/const VERSION='0\.9\.9'/)})
