import { AlertTriangle, CheckCircle2, Info } from 'lucide-react'
import { analyzeDataHealth } from './lib/dataHealth.js'

export default function DataHealth({data,update}){
  const {issues,coverage}=analyzeDataHealth(data),acknowledged=data.dataHealthAcknowledgements||[],active=issues.filter(x=>!x.id||!acknowledged.includes(x.id)),reviewed=issues.filter(x=>x.id&&acknowledged.includes(x.id)),warnings=active.filter(x=>x.level==='warning').length
  const acknowledge=issue=>update({...data,dataHealthAcknowledgements:[...new Set([...acknowledged,issue.id])]})
  const restore=issue=>update({...data,dataHealthAcknowledgements:acknowledged.filter(id=>id!==issue.id)})
  const item=(issue,index,reviewedItem=false)=><article className={`health-item ${issue.level}`} key={issue.id||`${issue.kind}-${index}`}>{issue.level==='warning'?<AlertTriangle size={18}/>:<Info size={18}/>}<div><strong>{issue.title}</strong><p>{issue.detail}</p>{issue.acknowledgeable&&<button type="button" className="secondary health-review-action" onClick={()=>reviewedItem?restore(issue):acknowledge(issue)}>{reviewedItem?'Review this again':issue.acknowledgementLabel}</button>}</div></article>
  return <section id="data-health" className="panel content-panel data-health"><div className="data-health-head"><div><span className="kicker">DATA QUALITY</span><h2>Data health</h2></div><span className={warnings?'health-count warning':'health-count'}>{warnings||'No'} {warnings===1?'warning':'warnings'}</span></div><p className="muted">These checks identify records worth reviewing. Debt Free never removes or changes them automatically.</p>{active.length?<div className="health-list">{active.map((issue,index)=>item(issue,index))}</div>:<div className="health-clear"><CheckCircle2 size={20}/><span>No unresolved data-quality findings were found.</span></div>}{reviewed.length>0&&<details className="coverage-detail reviewed-findings"><summary>Reviewed findings ({reviewed.length})</summary><p>These records are intentionally retained and no longer count as unresolved warnings.</p><div className="health-list">{reviewed.map((issue,index)=>item(issue,index,true))}</div></details>}<details className="coverage-detail"><summary>Historical coverage</summary>{coverage.first?<><p>Recorded activity currently spans {coverage.first} through {coverage.last}. A quiet month may mean lower activity or incomplete entry; Debt Free cannot assume which.</p><div className="coverage-grid">{coverage.months.map(month=><span key={month.month}><b>{month.month}</b>{month.entries} activit{month.entries===1?'y':'ies'} · {month.income||'No'} income entr{month.income===1?'y':'ies'}</span>)}</div></>:<p>No dated activity has been recorded yet.</p>}</details></section>
}
