import React,{useEffect,useMemo,useRef,useState} from 'react'
import { CalendarDays, CheckCircle2, Pencil, Plus, X } from 'lucide-react'
import { cashFlowForecast, INCOME_FREQUENCIES, readyIncomeOccurrences, saveIncomeSchedule, setIncomeScheduleActive } from './lib/incomeForecast.js'
import { localDate } from './lib/finance.js'

const money=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'})
const dateLabel=value=>new Date(`${value}T12:00:00`).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})

export default function IncomeForecast({data,update,onConfirmIncome,now=new Date()}){
  const [form,setForm]=useState(null),[error,setError]=useState(''),dialogRef=useRef(null),openerRef=useRef(null)
  const forecast=useMemo(()=>cashFlowForecast(data,now),[data,now]),ready=useMemo(()=>readyIncomeOccurrences(data,now),[data,now]),schedules=data.incomeSchedules||[]
  const close=()=>setForm(null)
  const open=item=>{openerRef.current=document.activeElement;setError('');setForm(item?{...item}:{name:'Paycheck',amount:'',accountId:data.accounts.find(a=>a.type==='checking')?.id||data.accounts.find(a=>a.type!=='credit')?.id||'',frequency:'biweekly',nextDate:localDate(),active:true})}
  useEffect(()=>{if(!form)return;dialogRef.current?.querySelector('input')?.focus();return()=>openerRef.current?.focus?.()},[Boolean(form)])
  const keys=e=>{if(e.key==='Escape'){close();return}if(e.key!=='Tab')return;const items=[...e.currentTarget.querySelectorAll('button:not([disabled]),input:not([disabled]),select:not([disabled])')],first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}
  const save=e=>{e.preventDefault();try{if(update(saveIncomeSchedule(data,form))===false){setError('Expected income could not be saved. Your existing data was not changed.');return}close()}catch(problem){setError(problem.message)}}
  const toggle=item=>{try{update(setIncomeScheduleActive(data,item.id,item.active===false))}catch(problem){setError(problem.message)}}
  const coverage=forecast.coverageBeforeIncome
  return <section className="panel content-panel income-forecast">
    <div className="income-forecast-head"><div><span className="kicker">LOOK AHEAD</span><h2>Payday forecast</h2><p className="muted">Expected income helps explain timing without changing today’s balances.</p></div><button className="secondary" type="button" onClick={()=>open()}><Plus size={15}/> Expected income</button></div>
    {ready.length>0&&<div className="ready-income-list">{ready.map(item=><div className="ready-income" key={item.id}><CheckCircle2 size={22}/><div><span>READY TO CONFIRM</span><strong>{item.name} · {money.format(item.amount)}</strong><small>Expected {dateLabel(item.date)}. Confirm the real deposit before it changes your account balance.</small></div><button className="primary" type="button" onClick={()=>onConfirmIncome?.(item)}>Confirm or edit amount</button></div>)}</div>}
    {forecast.nextIncome?<div className="forecast-grid">
      <div><span>Next expected deposit</span><strong>{money.format(forecast.nextIncome.amount)}</strong><small>{forecast.nextIncome.name} · {dateLabel(forecast.nextIncome.date)}</small></div>
      <div className={coverage<0?'forecast-negative':''}><span>Due before payday</span><strong>{money.format(forecast.dueBeforeIncome)}</strong><small>{coverage<0?`${money.format(Math.abs(coverage))} short before the deposit`:`Covered with ${money.format(coverage)} left`}</small></div>
      <div className={forecast.projectedCash<0?'forecast-negative':''}><span>Projected 30-day cash</span><strong>{money.format(forecast.projectedCash)}</strong><small>{money.format(forecast.expectedIncome)} expected income · {money.format(forecast.obligationsDue)} tracked obligations</small></div>
    </div>:<div className="forecast-empty"><CalendarDays size={21}/><div><strong>No expected income schedule yet</strong><p>Add your next payday to separate a temporary timing gap from a true cash shortage.</p></div></div>}
    <p className="forecast-disclaimer">Forecast only: it includes scheduled income and tracked cash obligations, but not future groceries, fuel, or other spending you have not entered. Log the real deposit and link it to its schedule so it is not counted twice.</p>
    {schedules.length>0&&<div className="income-schedule-list">{schedules.map(item=><div key={item.id}><div><strong>{item.name}</strong><small>{money.format(item.amount)} · {INCOME_FREQUENCIES.find(([value])=>value===item.frequency)?.[1]||item.frequency} · next {dateLabel(item.nextDate)}{item.active===false?' · Paused':''}</small></div><div><button type="button" className="icon-button" aria-label={`Edit ${item.name}`} onClick={()=>open(item)}><Pencil size={15}/></button><button type="button" className="secondary compact" onClick={()=>toggle(item)}>{item.active===false?'Resume':'Pause'}</button></div></div>)}</div>}
    {form&&<div className="modal-backdrop" onMouseDown={close}><form ref={dialogRef} className="modal income-schedule-modal" role="dialog" aria-modal="true" aria-label={form.id?'Edit expected income':'Add expected income'} onSubmit={save} onKeyDown={keys} onMouseDown={e=>e.stopPropagation()}><button type="button" className="close" aria-label="Close dialog" onClick={close}><X/></button><span className="kicker">CASH FLOW FORECAST</span><h2>{form.id?'Edit expected income':'Add expected income'}</h2>{error&&<p className="save-error" role="alert">{error}</p>}<label>Income name<input required value={form.name||''} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Expected net deposit<input required type="number" inputMode="decimal" min=".01" step=".01" value={form.amount||''} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>Deposit account<select required value={form.accountId||''} onChange={e=>setForm({...form,accountId:e.target.value})}><option value="">Choose account</option>{data.accounts.filter(a=>a.type!=='credit').map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><div className="forecast-form-row"><label>Frequency<select value={form.frequency||'biweekly'} onChange={e=>setForm({...form,frequency:e.target.value})}>{INCOME_FREQUENCIES.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Next expected deposit<input required type="date" value={form.nextDate||localDate()} onChange={e=>setForm({...form,nextDate:e.target.value})}/></label></div>{form.frequency==='semimonthly'&&<label>Other payday (day of month)<input required type="number" inputMode="numeric" min="1" max="31" value={form.secondPayDay||''} onChange={e=>setForm({...form,secondPayDay:e.target.value})}/></label>}<p className="modal-note">Use your expected take-home amount. This creates a forecast only; it does not increase the account balance.</p><button className="primary submit" type="submit">Save expected income</button></form></div>}
  </section>
}
