import { useEffect, useRef, useState } from 'react'
import PaymentAssignments from './PaymentAssignments.jsx'
import { confirmBillCycle, localDate, reconcileAccount, recordRefund, reassignPayment, saveStatement, statementTotals, cycleTotals, removeStatement } from './lib/finance.js'
import './v090.css'

const money=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'})
export function AccessibleDialog({title,onClose,children}) {
  const ref=useRef(null),opener=useRef(document.activeElement)
  useEffect(()=>{ref.current?.querySelector('input,select,button')?.focus();return()=>opener.current?.focus?.()},[])
  const keys=e=>{if(e.key==='Escape'){e.stopPropagation();onClose()}if(e.key==='Tab'){const items=[...ref.current.querySelectorAll('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled)')].filter(x=>x.getClientRects().length),first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}
  return <div className="reliable-backdrop"><section ref={ref} className="reliable-dialog" role="dialog" aria-modal="true" aria-label={title} onKeyDown={keys}><h2>{title}</h2>{children}<button type="button" className="secondary" onClick={onClose}>Cancel</button></section></div>
}
export default function ReliabilityCenter({data,update,page,onPayBill}) {
  const [mode,setMode]=useState(''),[form,setForm]=useState({}),[error,setError]=useState('')
  const start=(mode,form={})=>{setMode(mode);setForm(mode==='bill'?{...form,dueDate:data.billCycles.find(c=>c.id===form.id)?.dueDate}:form);setError('')}
  const field=(key,value)=>setForm(f=>({...f,[key]:value}))
  const submit=e=>{e.preventDefault();try{let next;if(mode==='statement')next=saveStatement(data,form);if(mode==='bill')next=confirmBillCycle(data,form.id,form.amount,undefined,form.dueDate);if(mode==='reconcile')next=reconcileAccount(data,form);if(mode==='refund')next=recordRefund(data,form);if(mode==='allocate')next=reassignPayment(data,form.id,form.target,form.kind);if(update(next)!==false)setMode('');else setError('Nothing was saved. Browser storage may be full or another tab changed your records. Close this window to read the save warning.')}catch(e){setError(e.message)}}
  const cards=data.accounts.filter(a=>a.type==='credit'),today=localDate()
  return <>
    {page==='dashboard'&&data.payments.some(p=>p.assignmentStatus!=='confirmed')&&<section className="panel content-panel warning-text"><p>Some payments are not assigned to a statement. They remain in your history, but do not count toward minimums yet. Amounts shown as due may be overstated until you review payment assignments under Debts.</p></section>}
    {page==='dashboard'&&<section className="panel content-panel reliability-notice"><h2>What this estimate includes</h2><p>Cash after tracked obligations subtracts unpaid cash-funded bills and recorded card-statement minimums. It includes overdue items and the next recorded occurrences—not a payday budget. Savings are included in cash; no emergency fund, groceries, or other unlogged spending is protected.</p><p>Card-funded subscriptions increase card debt when logged; their full amount is not subtracted from cash again. Future card statements are unknown until you add them. Check your bank’s current balances and statements before deciding what to spend.</p>{cards.some(a=>!data.cardStatements.some(s=>s.cardId===a.id&&s.dueDate>=today&&!s.needsReview))&&<p className="warning-text">A card needs a current, confirmed statement. Review Statements under Debts; this estimate may omit future minimums.</p>}{(data.cardStatements.some(s=>s.needsReview)||data.billCycles.some(c=>c.needsReview))&&<p className="warning-text">Imported statement/bill assignments need review. Balances and payment amounts were preserved; check dates and allocations under Debts and Bills.</p>}<p>Payoff estimate: {money.format(data.extra)} extra each month, recorded APRs and minimums, no new charges or fees. Interest is an approximation, not a lender quote.</p></section>}
    {page==='debts'&&<section className="panel content-panel"><h2>Statements</h2><p>Confirm each statement from your issuer. Extra payments stay on the selected statement; paying a minimum does not create the next one.</p><button className="primary" type="button" disabled={!cards.length} onClick={()=>start('statement',{cardId:cards[0]?.id,dueDate:today,minimum:''})}>Add statement</button>{data.cardStatements.slice().sort((a,b)=>b.dueDate.localeCompare(a.dueDate)).map(s=>{const t=statementTotals(s,data.payments);return <div className="reliable-row" key={s.id}><div><strong>{cards.find(a=>a.id===s.cardId)?.name} · Due {s.dueDate}</strong><small>{money.format(s.minimum)} minimum · {money.format(t.actualPaid)} paid · {s.supersededBy?`Carried into statement ${data.cardStatements.find(x=>x.id===s.supersededBy)?.dueDate}`:t.remaining?`${money.format(t.remaining)} remaining${s.dueDate<today?' · Overdue':''}`:'Minimum met'}{s.needsReview?' · Review imported statement':''}</small></div><button className="secondary" onClick={()=>start('statement',s)}>{s.needsReview?'Review statement':'Edit statement'}</button></div>})}<PaymentAssignments data={data} update={update}/></section>}
    {page==='bills'&&<section className="panel content-panel"><h2>Bill occurrences</h2><p>Each occurrence keeps its own amount and payments. Confirm the actual invoice amount—even if it differs from the estimate. Autopay is a reminder, not proof of payment.</p>{data.billCycles.slice().sort((a,b)=>b.dueDate.localeCompare(a.dueDate)).map(c=>{const bill=data.bills.find(b=>b.id===c.billId),t=cycleTotals(c,data.billPayments);return <div className="reliable-row" key={c.id}><div><strong>{bill?.name} · {c.dueDate}</strong><small>{money.format(c.expectedAmount)} expected · {c.actualAmount==null?'Actual not confirmed':`${money.format(c.actualAmount)} actual`} · {money.format(t.actualPaid)} paid/charged · {t.remaining?`${money.format(t.remaining)} remaining${c.dueDate<today?' · Overdue':''}`:'Complete'}{c.needsReview?' · Review imported occurrence':''}</small></div><div className="reliable-actions"><button className="secondary" onClick={()=>start('bill',{id:c.id,amount:c.actualAmount??c.expectedAmount})}>Confirm actual</button>{t.remaining>0&&<button className="primary" onClick={()=>onPayBill(bill,c)}>Log payment/charge</button>}</div></div>})}<details><summary>Review bill-payment allocations</summary>{data.billPayments.map(p=><div className="reliable-row" key={p.id}><span>{p.billName} · {money.format(p.amount)} · {data.billCycles.find(c=>c.id===p.cycleId)?.dueDate}</span><button className="secondary" onClick={()=>start('allocate',{id:p.id,kind:'bill',owner:p.billId,target:p.cycleId||''})}>Change occurrence</button></div>)}</details></section>}
    {page==='accounts'&&<section className="panel content-panel"><h2>Check balances against your bank</h2><p>First look for missing or duplicated entries. If a balance still differs, record an explained adjustment. Adjustments are not income or spending and do not erase history.</p>{data.accounts.map(a=><div className="reliable-row" key={a.id}><span>{a.name} · Last checked: {a.reconciledAt?new Date(a.reconciledAt).toLocaleDateString():'Not checked'}</span><button className="secondary" onClick={()=>start('reconcile',{accountId:a.id,balance:a.balance,reason:''})}>Reconcile balance</button></div>)}<details><summary>Balance adjustment history</summary>{data.adjustments.map(a=><div className="reliable-row" key={a.id}><span>{data.accounts.find(x=>x.id===a.accountId)?.name} · {money.format(a.before)} → {money.format(a.after)} · {new Date(a.date).toLocaleDateString()}<small>{a.reason}</small></span></div>)}</details></section>}
    {page==='transactions'&&<section className="panel content-panel"><h2>Refunds</h2><p>Record a refund on the day it arrived. It reduces net spending in its category and increases cash or reduces card debt; it is not income.</p><button className="secondary" disabled={!data.accounts.length} onClick={()=>start('refund',{accountId:data.accounts[0]?.id,date:today,category:'Other',historical:false})}>Log refund</button></section>}
    {mode&&<AccessibleDialog title={{statement:'Confirm card statement',bill:'Confirm actual bill amount',reconcile:'Reconcile balance',refund:'Log refund',allocate:'Correct payment assignment'}[mode]} onClose={()=>setMode('')}><form onSubmit={submit}>
      {mode==='statement'&&<><label>Card<select required disabled={Boolean(form.id)} value={form.cardId} onChange={e=>field('cardId',e.target.value)}>{cards.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Statement due date<input required type="date" value={form.dueDate} onClick={e=>{try{e.currentTarget.showPicker?.()}catch{}}} onChange={e=>field('dueDate',e.target.value)}/></label><label>Original minimum due<input required type="number" min="0" step=".01" value={form.minimum} onChange={e=>field('minimum',e.target.value)}/></label><p>Use the original minimum from this statement, not today’s remaining card balance. Review imported payment allocations below if needed.</p></>}
      {mode==='statement'&&<label className="check-line"><input type="checkbox" checked={Boolean(form.includesPastDue)} onChange={e=>field('includesPastDue',e.target.checked)}/> This minimum includes unpaid earlier minimums. Carry them into this statement instead of reserving them twice.</label>}
      {mode==='statement'&&form.id&&<button type="button" className="secondary" onClick={()=>{if(!confirm('Remove this statement? Any linked payments must be reassigned or left unassigned first.'))return;try{if(update(removeStatement(data,form.id))!==false)setMode('');else setError('Nothing was saved. Check the save warning.')}catch(e){setError(e.message)}}}>Remove incorrect statement</button>}
      {mode==='bill'&&<><label>Due date for this occurrence<input required type="date" value={form.dueDate||''} onClick={e=>{try{e.currentTarget.showPicker?.()}catch{}}} onChange={e=>field('dueDate',e.target.value)}/></label><label>Actual amount for this occurrence<input required type="number" min="0" step=".01" value={form.amount} onChange={e=>field('amount',e.target.value)}/></label><p>This changes only this occurrence, not future estimates. Use zero only if no payment is actually due.</p></>}
      {mode==='reconcile'&&<><label>Bank’s current balance<input required type="number" step=".01" value={form.balance} onChange={e=>field('balance',e.target.value)}/></label><label>Reason for adjustment<textarea required value={form.reason} onChange={e=>field('reason',e.target.value)}/></label><p>For a card, a negative balance means a credit in your favor.</p></>}
      {mode==='refund'&&<><label>Received on<input required type="date" max={today} value={form.date} onClick={e=>{try{e.currentTarget.showPicker?.()}catch{}}} onChange={e=>field('date',e.target.value)}/></label><label>Account<select required value={form.accountId} onChange={e=>field('accountId',e.target.value)}>{data.accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Merchant<input required value={form.merchant||''} onChange={e=>field('merchant',e.target.value)}/></label><label>Refund amount<input required type="number" min=".01" step=".01" value={form.amount||''} onChange={e=>field('amount',e.target.value)}/></label><label>Category<select value={form.category} onChange={e=>field('category',e.target.value)}>{['Groceries','Dining','Fuel','Shopping','Subscriptions','Entertainment','Utilities','Health','Travel','Housing','Insurance','Interest','Other'].map(c=><option key={c}>{c}</option>)}</select></label><label className="check-line"><input type="checkbox" checked={form.historical} onChange={e=>field('historical',e.target.checked)}/> Already included in my current balance</label></>}
      {mode==='allocate'&&<><label>{form.kind==='card'?'Statement':'Bill occurrence'}<select required value={form.target} onChange={e=>field('target',e.target.value)}><option value="">Choose</option>{(form.kind==='card'?data.cardStatements:data.billCycles).filter(x=>(form.kind==='card'?x.cardId:x.billId)===form.owner).map(x=><option key={x.id} value={x.id}>{x.dueDate}</option>)}</select></label><p>This corrects the assignment only. The payment amount and account balances will not change.</p></>}
      {error&&<p role="alert">{error}</p>}<button className="primary" type="submit">Save</button>
    </form></AccessibleDialog>}
  </>
}
