import { useEffect, useRef, useState } from 'react'
import { createPortal } from 'react-dom'
import { Check, Cloud, Download, HardDrive, MonitorCog, Settings, ShieldCheck, Upload, X } from 'lucide-react'
import { BACKUP_SCHEMA, RELEASE_VERSION, STORAGE_KEY } from './release.js'
import { validateData } from './lib/backup.js'
import { parseBackup } from './lib/storage.js'
import { diagnosticPayload } from './lib/diagnosticExport.js'

function readStoredData(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'null')}catch{return null}}
function safeRead(key){try{return localStorage.getItem(key)}catch{return null}}
function downloadJson(payload,filename){const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}
function backupPayload(data){return{schema:BACKUP_SCHEMA,app:'Debt Free',version:RELEASE_VERSION,exportedAt:new Date().toISOString(),data}}

export default function SettingsCenter(){
 const [open,setOpen]=useState(false),[message,setMessage]=useState(''),[navTarget,setNavTarget]=useState(null)
 const [mode,setMode]=useState(()=>safeRead('debt-free-mode')||'system')
 const [accent,setAccent]=useState(()=>safeRead('debt-free-accent')||'mint')
 const inputRef=useRef(null),panelRef=useRef(null),data=readStoredData()
 const [,refresh]=useState(0)
 useEffect(()=>{const changed=()=>refresh(x=>x+1);window.addEventListener('debt-free-data-updated',changed);return()=>window.removeEventListener('debt-free-data-updated',changed)},[])
 useEffect(()=>{if(!open)return;const opener=document.activeElement,panel=panelRef.current;panel?.querySelector('button')?.focus();const trap=e=>{if(e.key!=='Tab')return;const items=[...panel.querySelectorAll('button:not(:disabled),input:not(:disabled),select:not(:disabled)')].filter(x=>x.getClientRects().length),first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}};panel?.addEventListener('keydown',trap);return()=>{panel?.removeEventListener('keydown',trap);opener?.focus?.()}},[open])
 const counts={accounts:data?.accounts?.length||0,activity:data?.transactions?.length||0,payments:(data?.payments?.length||0)+(data?.billPayments?.length||0),bills:data?.bills?.length||0}
 useEffect(()=>setNavTarget(document.querySelector('.sidebar nav')),[])
 useEffect(()=>{document.documentElement.dataset.debtMode=mode;try{localStorage.setItem('debt-free-mode',mode)}catch{setMessage('Appearance changed for this session; browser storage is unavailable.')}},[mode])
 useEffect(()=>{document.documentElement.dataset.debtAccent=accent;try{localStorage.setItem('debt-free-accent',accent)}catch{setMessage('Appearance changed for this session; browser storage is unavailable.')}},[accent])
 const exportBackup=()=>{const current=readStoredData();if(!validateData(current)){setMessage('There is no valid Debt Free data to back up yet. Use Download stored data for recovery.');return}const now=new Date(),stamp=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;downloadJson(backupPayload(current),`debt-free-backup-v${RELEASE_VERSION}-${stamp}.json`);try{localStorage.setItem('debt-free-last-backup',new Date().toISOString())}catch{}window.dispatchEvent(new Event('debt-free-backup-updated'));setMessage('Backup download started. Check that the file was saved.')}
 const exportDiagnostic=()=>{const current=readStoredData();if(!validateData(current)){setMessage('There is no valid Debt Free data to review yet.');return}const now=new Date(),stamp=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;downloadJson(diagnosticPayload(current,{version:RELEASE_VERSION}),`debt-free-anonymized-review-v${RELEASE_VERSION}-${stamp}.json`);setMessage('Anonymized review file downloaded. Names were replaced, but financial values remain sensitive.')}
 const restoreBackup=async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;try{if(file.size>20*1024*1024)throw new Error('This file is too large to safely restore in this browser.');const incoming=parseBackup(await file.text());if(!confirm(`Replace this browser’s records with ${incoming.accounts.length} accounts and ${incoming.transactions.length} activity entries from this backup? Current stored data will be retained as a recovery copy.`))return;const raw=localStorage.getItem(STORAGE_KEY);if(raw)localStorage.setItem(`${STORAGE_KEY}-pre-restore`,raw);localStorage.setItem(STORAGE_KEY,JSON.stringify(incoming));window.location.reload()}catch(error){setMessage(`${error.message||'Restore failed.'} Current records were not replaced.`)}}
 const recover=()=>{try{const raw=localStorage.getItem(`${STORAGE_KEY}-previous`);if(!raw)throw new Error('No previous saved state is available.');const incoming=parseBackup(raw);if(!confirm('Restore the previous saved state? This replaces the current records; a recovery copy of them will be kept.'))return;const current=localStorage.getItem(STORAGE_KEY);if(current)localStorage.setItem(`${STORAGE_KEY}-pre-restore`,current);localStorage.setItem(STORAGE_KEY,JSON.stringify(incoming));window.location.reload()}catch(error){setMessage(error.message)}}
 const exportRaw=()=>{try{const raw=localStorage.getItem(STORAGE_KEY);if(!raw){setMessage('No stored data is available.');return}downloadJson({recovery:true,storedText:raw},'debt-free-recovery.json');setMessage('Recovery download started. Keep this file; it is for troubleshooting, not direct backup restore.')}catch{setMessage('Browser storage cannot be read. Try another browser session or your saved backup.')}}
 const lastBackup=safeRead('debt-free-last-backup')
 const navButton=<button className="nav settings-nav" type="button" onClick={()=>setOpen(true)}><Settings size={17}/>Settings</button>
 return <>{navTarget&&createPortal(navButton,navTarget)}{open&&<div className="settings-backdrop" onMouseDown={()=>setOpen(false)} onKeyDown={e=>{if(e.key==='Escape')setOpen(false)}}><section ref={panelRef} className="settings-panel" role="dialog" aria-modal="true" aria-label="Settings" onMouseDown={e=>e.stopPropagation()}><button className="settings-close" type="button" onClick={()=>setOpen(false)} aria-label="Close settings"><X size={18}/></button><div className="settings-heading"><div className="settings-icon"><Settings size={22}/></div><div><span className="kicker">SETTINGS</span><h2>Debt Free</h2><p>Version {RELEASE_VERSION}</p></div></div>
 <div className="settings-section"><div className="settings-section-title"><Cloud size={18}/><div><strong>Account & sync</strong><span>Cloud accounts are planned for Firebase.</span></div></div><div className="settings-status"><span>Current storage</span><strong><HardDrive size={15}/> This browser only</strong></div><p>Your financial records currently stay on this device. When cloud sync is introduced, this section will become the home for sign-in, sync status and account management.</p></div>
 <div className="settings-section"><div className="settings-section-title"><ShieldCheck size={18}/><div><strong>Data & backup</strong><span>Protect your local financial history.</span></div></div><div className="data-counts"><span><b>{counts.accounts}</b> accounts</span><span><b>{counts.activity}</b> activity</span><span><b>{counts.payments}</b> payments</span><span><b>{counts.bills}</b> bills</span></div><div className="settings-warning"><ShieldCheck size={17}/><span>Clearing browser/site data can erase local records. Keep a recent backup while Debt Free is local-only.</span></div><div className="settings-actions"><button type="button" className="primary" onClick={exportBackup}><Download size={17}/> Download backup</button><button type="button" className="secondary" onClick={()=>inputRef.current?.click()}><Upload size={17}/> Restore backup</button><button type="button" className="secondary" onClick={exportDiagnostic}><ShieldCheck size={17}/> Download anonymized review</button></div><p className="diagnostic-note">For troubleshooting and review only. It replaces account, merchant, bill, and income-source names. Amounts, dates, categories, balances, and credit scores remain visible so calculations can be checked. It cannot be restored into the app.</p><input ref={inputRef} className="hidden-file" type="file" accept="application/json,.json" onChange={restoreBackup}/><small>{lastBackup?`Last backup: ${new Date(lastBackup).toLocaleString()}`:'No backup downloaded from this browser yet.'}</small>{message&&<div className="backup-message">{message}</div>}</div>
 <div className="settings-section"><h3>Recovery</h3><p>Local recovery copies do not replace downloaded backups. Clearing browser data removes these copies too.</p><div className="settings-actions"><button type="button" className="secondary" onClick={recover}>Restore previous saved state</button><button type="button" className="secondary" onClick={exportRaw}>Download stored data</button></div></div>
 <div className="settings-section"><div className="settings-section-title"><MonitorCog size={18}/><div><strong>Appearance</strong><span>Match your device or choose a clear light/dark workspace.</span></div></div><div className="appearance-label">Mode</div><div className="theme-picker">{[['system','System'],['light','Light'],['dark','Dark']].map(([id,label])=><button key={id} type="button" className={mode===id?'theme-option active':'theme-option'} onClick={()=>setMode(id)}><i className={`theme-swatch mode-${id}`}/><span>{label}</span>{mode===id&&<Check size={15}/>}</button>)}</div><div className="appearance-label">Accent</div><div className="accent-picker">{[['mint','Mint'],['blue','Blue'],['violet','Violet'],['amber','Amber']].map(([id,label])=><button key={id} type="button" className={accent===id?'accent-option active':'accent-option'} onClick={()=>setAccent(id)}><i className={`accent-swatch ${id}`}/><span>{label}</span>{accent===id&&<Check size={14}/>}</button>)}</div></div>
 </section></div>}</>}
