import { useEffect, useRef, useState } from 'react'
import { createPortal } from 'react-dom'
import { Check, Cloud, Download, MonitorCog, RefreshCw, Settings, ShieldCheck, Trash2, Upload, X } from 'lucide-react'
import { BACKUP_SCHEMA, RELEASE_VERSION, STORAGE_KEY } from './release.js'
import { parseBackup } from './lib/storage.js'
import { diagnosticPayload } from './lib/diagnosticExport.js'
import { getActiveData, getCloudSession } from './lib/cloudState.js'

function readStoredData(){const cloud=getActiveData();if(cloud)return cloud;try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'null')}catch{return null}}
function safeRead(key){try{return localStorage.getItem(key)}catch{return null}}
function downloadJson(payload,filename){const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}
function backupPayload(data){return{schema:BACKUP_SCHEMA,app:'Debt Free',version:RELEASE_VERSION,exportedAt:new Date().toISOString(),data}}
function hasExportableData(data){return Boolean(data&&typeof data==='object'&&Array.isArray(data.accounts)&&Array.isArray(data.transactions)&&Array.isArray(data.payments)&&Array.isArray(data.bills))}

export default function SettingsCenter(){
 const [open,setOpen]=useState(false),[message,setMessage]=useState(''),[navTarget,setNavTarget]=useState(null),[cloudTick,setCloudTick]=useState(0)
 const [mode,setMode]=useState(()=>safeRead('debt-free-mode')||'system')
 const [accent,setAccent]=useState(()=>safeRead('debt-free-accent')||'mint')
 const inputRef=useRef(null),panelRef=useRef(null),data=readStoredData()
 const [,refresh]=useState(0)
 useEffect(()=>{const changed=()=>refresh(x=>x+1);window.addEventListener('debt-free-data-updated',changed);return()=>window.removeEventListener('debt-free-data-updated',changed)},[])
 useEffect(()=>{const changed=()=>setCloudTick(x=>x+1);window.addEventListener('debt-free-cloud-updated',changed);return()=>window.removeEventListener('debt-free-cloud-updated',changed)},[])
 useEffect(()=>{if(!open)return;const opener=document.activeElement,panel=panelRef.current;panel?.querySelector('button')?.focus();const trap=e=>{if(e.key!=='Tab')return;const items=[...panel.querySelectorAll('button:not(:disabled),input:not(:disabled),select:not(:disabled)')].filter(x=>x.getClientRects().length),first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}};panel?.addEventListener('keydown',trap);return()=>{panel?.removeEventListener('keydown',trap);opener?.focus?.()}},[open])
 const counts={accounts:data?.accounts?.length||0,activity:data?.transactions?.length||0,payments:(data?.payments?.length||0)+(data?.billPayments?.length||0),bills:data?.bills?.length||0}
 useEffect(()=>setNavTarget(document.querySelector('.sidebar nav')),[cloudTick])
 useEffect(()=>{document.documentElement.dataset.debtMode=mode;try{localStorage.setItem('debt-free-mode',mode)}catch{setMessage('Appearance changed for this session; browser storage is unavailable.')}},[mode])
 useEffect(()=>{document.documentElement.dataset.debtAccent=accent;try{localStorage.setItem('debt-free-accent',accent)}catch{setMessage('Appearance changed for this session; browser storage is unavailable.')}},[accent])
 const exportBackup=()=>{const current=readStoredData();if(!hasExportableData(current)){setMessage('There are no Debt Free records to back up yet.');return}const now=new Date(),stamp=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;downloadJson(backupPayload(current),`debt-free-backup-v${RELEASE_VERSION}-${stamp}.json`);try{localStorage.setItem('debt-free-last-backup',new Date().toISOString())}catch{}window.dispatchEvent(new Event('debt-free-backup-updated'));setMessage('Backup download started. Check that the file was saved.')}
 const exportDiagnostic=()=>{const current=readStoredData();if(!hasExportableData(current)){setMessage('There are no Debt Free records to review yet.');return}const now=new Date(),stamp=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;downloadJson(diagnosticPayload(current,{version:RELEASE_VERSION}),`debt-free-anonymized-review-v${RELEASE_VERSION}-${stamp}.json`);setMessage('Anonymized review file downloaded. Names were replaced, but financial values remain sensitive.')}
 const restoreBackup=async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;try{if(file.size>20*1024*1024)throw new Error('This file is too large to safely restore in this browser.');const incoming=parseBackup(await file.text()),session=getCloudSession();if(session.status==='ready'&&session.actions?.restore){if(!confirm(`Replace your private cloud records with ${incoming.accounts.length} accounts and ${incoming.transactions.length} activity entries from this backup?`))return;await session.actions.restore(incoming);setMessage('Backup restored to your private cloud record.');return}if(!confirm(`Replace this browser’s records with ${incoming.accounts.length} accounts and ${incoming.transactions.length} activity entries from this backup? Current stored data will be retained as a recovery copy.`))return;const raw=localStorage.getItem(STORAGE_KEY);if(raw)localStorage.setItem(`${STORAGE_KEY}-pre-restore`,raw);localStorage.setItem(STORAGE_KEY,JSON.stringify(incoming));window.location.reload()}catch(error){setMessage(`${error.message||'Restore failed.'} Current records were not replaced.`)}}
 const recover=()=>{try{const raw=localStorage.getItem(`${STORAGE_KEY}-previous`);if(!raw)throw new Error('No previous saved state is available.');const incoming=parseBackup(raw);if(!confirm('Restore the previous saved state? This replaces the current records; a recovery copy of them will be kept.'))return;const current=localStorage.getItem(STORAGE_KEY);if(current)localStorage.setItem(`${STORAGE_KEY}-pre-restore`,current);localStorage.setItem(STORAGE_KEY,JSON.stringify(incoming));window.location.reload()}catch(error){setMessage(error.message)}}
 const exportRaw=()=>{try{const raw=localStorage.getItem(STORAGE_KEY);if(!raw){setMessage('No stored data is available.');return}downloadJson({recovery:true,storedText:raw},'debt-free-recovery.json');setMessage('Recovery download started. Keep this file; it is for troubleshooting, not direct backup restore.')}catch{setMessage('Browser storage cannot be read. Try another browser session or your saved backup.')}}
 const reloadCloud=async()=>{try{await getCloudSession().actions?.reload?.();setMessage('Latest cloud copy loaded.')}catch(error){setMessage(error.message||'Could not reload the cloud copy.')}}
 const retryCloud=async()=>{try{await getCloudSession().actions?.retry?.();setMessage('Latest changes saved to the cloud.')}catch(error){setMessage(error.message||'Still unable to save. Download a backup before leaving this page.')}}
 const clearCloud=async()=>{const session=getCloudSession();if(!confirm('Clear every account, activity entry, bill, payment and score from this cloud workspace? Download a backup first if you may need these records again.'))return;try{await session.actions?.clear?.();setMessage('Your cloud workspace is now blank. Your Google sign-in remains available.')}catch(error){setMessage(error.message||'Cloud workspace could not be cleared. Nothing was changed.')}}
 const lastBackup=safeRead('debt-free-last-backup'),session=getCloudSession(),cloudReady=session.status==='ready',cloudName=session.user?.displayName||session.user?.email||'Signed-in account'
 const navButton=<button className="nav settings-nav" type="button" onClick={()=>setOpen(true)}><Settings size={17}/>Settings</button>
 return <>{navTarget&&createPortal(navButton,navTarget)}{open&&<div className="settings-backdrop" onMouseDown={()=>setOpen(false)} onKeyDown={e=>{if(e.key==='Escape')setOpen(false)}}><section ref={panelRef} className="settings-panel" role="dialog" aria-modal="true" aria-label="Settings" onMouseDown={e=>e.stopPropagation()}><button className="settings-close" type="button" onClick={()=>setOpen(false)} aria-label="Close settings"><X size={18}/></button><div className="settings-heading"><div className="settings-icon"><Settings size={22}/></div><div><span className="kicker">SETTINGS</span><h2>Debt Free</h2><p>Version {RELEASE_VERSION}</p></div></div>
 <div className="settings-section"><div className="settings-section-title"><Cloud size={18}/><div><strong>Account & sync</strong><span>{cloudReady?'Your private records are connected to Firebase.':'Cloud connection is being checked.'}</span></div></div><div className="settings-status"><span>Current storage</span><strong><Cloud size={15}/>{cloudReady?' Private cloud':' Connecting…'}</strong></div>{cloudReady&&<><p>{cloudName} · {session.sync||'Saved in the cloud'}</p><div className="settings-actions">{session.sync?.includes("failed")&&<button type="button" className="primary" onClick={retryCloud}><RefreshCw size={16}/> Retry cloud save</button>}<button type="button" className="secondary" onClick={reloadCloud}><RefreshCw size={16}/> Reload latest cloud copy</button><button type="button" className="secondary" onClick={()=>session.actions?.signOut?.()}>Sign out</button></div></>}</div>
 <div className="settings-section"><div className="settings-section-title"><ShieldCheck size={18}/><div><strong>Data & backup</strong><span>Download a recovery copy whenever you make meaningful changes.</span></div></div><div className="data-counts"><span><b>{counts.accounts}</b> accounts</span><span><b>{counts.activity}</b> activity</span><span><b>{counts.payments}</b> payments</span><span><b>{counts.bills}</b> bills</span></div><div className="settings-warning"><ShieldCheck size={17}/><span>{cloudReady?'Your primary records are in your private cloud account. Downloads remain your independent recovery copy.':'Keep a recent backup while the cloud connection is being checked.'}</span></div><div className="settings-actions"><button type="button" className="primary" onClick={exportBackup}><Download size={17}/> Download backup</button><button type="button" className="secondary" onClick={()=>inputRef.current?.click()}><Upload size={17}/> Restore backup</button><button type="button" className="secondary" onClick={exportDiagnostic}><ShieldCheck size={17}/> Download anonymized review</button></div><p className="diagnostic-note">For troubleshooting and review only. It replaces account, merchant, bill, and income-source names. Amounts, dates, categories, balances, and credit scores remain visible so calculations can be checked. It cannot be restored into the app.</p><input ref={inputRef} className="hidden-file" type="file" accept="application/json,.json" onChange={restoreBackup}/><small>{lastBackup?`Last backup: ${new Date(lastBackup).toLocaleString()}`:'No backup downloaded from this browser yet.'}</small>{message&&<div className="backup-message">{message}</div>}</div>
 {!cloudReady&&<div className="settings-section"><h3>Local recovery</h3><p>Local recovery copies do not replace downloaded backups. Clearing browser data removes these copies too.</p><div className="settings-actions"><button type="button" className="secondary" onClick={recover}>Restore previous saved state</button><button type="button" className="secondary" onClick={exportRaw}>Download stored data</button></div></div>}
 {cloudReady&&<div className="settings-section settings-danger"><div className="settings-section-title"><ShieldCheck size={18}/><div><strong>Privacy & data control</strong><span>Your financial records stay in your signed-in private cloud workspace. Backups are your independent recovery copy.</span></div></div><p>Clearing the workspace removes all financial records from Debt Free but keeps this Google sign-in available to start again.</p><button type="button" className="secondary danger" onClick={clearCloud}><Trash2 size={16}/> Clear cloud workspace</button></div>}
 <div className="settings-section"><div className="settings-section-title"><MonitorCog size={18}/><div><strong>Appearance</strong><span>Match your device or choose a clear light/dark workspace.</span></div></div><div className="appearance-label">Mode</div><div className="theme-picker">{[['system','System'],['light','Light'],['dark','Dark']].map(([id,label])=><button key={id} type="button" className={mode===id?'theme-option active':'theme-option'} onClick={()=>setMode(id)}><i className={`theme-swatch mode-${id}`}/><span>{label}</span>{mode===id&&<Check size={15}/>}</button>)}</div><div className="appearance-label">Accent</div><div className="accent-picker">{[['mint','Mint'],['blue','Blue'],['violet','Violet'],['amber','Amber']].map(([id,label])=><button key={id} type="button" className={accent===id?'accent-option active':'accent-option'} onClick={()=>setAccent(id)}><i className={`accent-swatch ${id}`}/><span>{label}</span>{accent===id&&<Check size={14}/>}</button>)}</div></div>
 </section></div>}</>}
